server:
  port: 8089

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/t1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dengyan



# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.ar: debug
# MyBatis-Plus 配置该演示无
